project:
  type: website
  output-dir: docs

website:
  title: "My super duper website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "More"
        menu:
          - talks.qmd
          - about.qmd 
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



