project:
  type: book
  output-dir: docs

book:
  title: "My Awesome Book"
  author: "Norah Jones"
  date: "3/4/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar:
    search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    code-download: true
  pdf:
    documentclass: scrreprt



